<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Pivot-Tables" data-toc-modified-id="Pivot-Tables-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Pivot Tables</a></span></li></ul></div>

# pivot/unpivot

In [46]:
df = pd.read_csv('data/life_expectancy_years.csv')

In [ ]:
# eplore data

In [47]:
# melt the normalized file, hold the country name and code variables, rename the melted columns
# id_vars, var_name, value_name

In [ ]:
# pivot the data by years
# index, columns, values

# Pivot Tables

Load the vehicles dataset. We can look at a pivot table where the index is vehicle class:

In [23]:
import pandas as pd
import numpy as np

vehicles = pd.read_csv('data/vehicles.csv')

In [24]:
vehicles.head()

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,555.437500,2100
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,555.437500,2550

In [26]:
vehicles.pivot_table(index=["Vehicle Class"])

,CO2 Emission Grams/Mile,City MPG,Combined MPG,Cylinders,Engine Displacement,Fuel Barrels/Year,Fuel Cost/Year,Highway MPG,Year
Vehicle Class,,,,,,,,,
Compact Cars,396.758088,20.570685,23.373385,4.837223,2.469296,14.705935,1612.295082,28.210222,2001.097589
Large Cars,484.391278,16.130310,18.936854,7.128588,4.152354,17.893457,1992.680827,23.989667,2004.792193
Midsize Cars,432.861095,18.950775,21.670441,5.665026,3.148929,16.059481,1768.028550,26.569776,2002.438100
Midsize Station Wagons,432.128533,18.360577,21.024038,5.173077,2.706490,16.029417,1826.682692,25.627404,2004.108173
Midsize-Large Station Wagons,452.981561,17.590837,19.924171,5.113744,2.847867,16.807043,1722.590837,23.984202,1989.941548
Minicompact Cars,443.861984,18.380363,21.028053,5.764026,3.123597,16.467255,1972.112211,25.611386,2004.628713
Minivan - 2WD,469.287896,16.679758,19.117825,5.800604,3.416012,17.370910,1758.459215,23.410876,2006.380665
Minivan - 4WD,504.595699,15.425532,17.638298,6.000000,3.570213,18.723079,1887.234043,21.531915,2005.063830
Small Pickup Trucks,450.039261,18.416031,20.257634,4.648855,2.686641,16.704702,1687.690840,23.255725,1988.938931
Small Pickup Trucks 2WD,454.361734,17.922693,19.997506,4.802993,3.014713,16.862666,1698.254364,23.324190,2001.623441
Small Pickup Trucks 4WD,497.689565,16.405000,18.125000,5.225000,3.427000,18.480509,1861.250000,20.820000,2004.840000
Small Sport Utility Vehicle 2WD,378.034759,21.147059,23.818182,4.657754,2.612299,14.026764,1466.443850,28.187166,2014.895722
Small Sport Utility Vehicle 4WD,403.410931,20.026316,22.421053,4.866397,2.718219,15.006553,1600.404858,26.342105,2014.979757
Small Station Wagons,383.149627,21.207148,23.839533,4.444931,2.160394,14.215901,1532.020423,28.226112,2001.119621
Special Purpose Vehicle,462.727273,21.000000,22.000000,4.000000,2.400000,17.372045,1650.000000,24.000000,2003.000000
Special Purpose Vehicle 2WD,523.669366,15.991394,17.726334,5.538726,3.269019,19.248030,1969.535284,20.567986,1992.359725
Special Purpose Vehicle 4WD,562.121707,15.042969,16.558594,6.015625,3.742969,20.867057,2114.062500,18.984375,1991.078125
Special Purpose Vehicles,554.603335,15.306268,16.755698,5.761396,3.479843,20.578362,2098.896011,19.190171,1991.693732
Special Purpose Vehicles/2wd,458.456349,18.500000,19.500000,5.000000,2.700000,17.003690,1725.000000,21.500000,1997.000000
Special Purpose Vehicles/4wd,522.764706,15.500000,17.000000,6.000000,3.000000,19.388824,1950.000000,19.000000,1997.000000
Sport Utility Vehicle - 2WD,487.995241,16.840248,18.824149,5.873065,3.577647,18.099545,1866.718266,22.261920,2006.261300
Sport Utility Vehicle - 4WD,531.005884,15.516098,17.298414,6.229697,3.764488,19.698987,2103.099471,20.341663,2006.257568
Standard Pickup Trucks,605.415356,13.822155,15.241887,6.777153,4.605712,22.478355,2263.349199,17.675465,1990.493726
Standard Pickup Trucks 2WD,551.421895,14.771253,16.542507,6.737949,4.411306,20.251536,2093.426819,19.560911,2003.083260
Standard Pickup Trucks 4WD,589.712622,13.813347,15.372263,6.930136,4.562774,21.808641,2228.936392,18.016684,2003.874870
Standard Pickup Trucks/2wd,687.684524,12.000000,13.000000,8.000000,5.700000,25.505536,2600.000000,15.500000,1995.000000
Standard Sport Utility Vehicle 2WD,487.407821,16.340782,18.614525,6.826816,4.466480,18.059814,1866.480447,22.709497,2014.972067
Standard Sport Utility Vehicle 4WD,505.193154,16.134474,18.129584,6.899756,4.266015,18.791048,2101.955990,21.691932,2014.946210
Subcompact Cars,414.484391,20.004344,22.626200,5.127572,2.622382,15.360171,1713.385917,27.126200,1998.316187
Two Seaters,498.090133,17.011211,19.514013,6.679933,3.600392,18.468285,2207.539238,23.941704,2003.746076
Vans,607.848459,13.710972,15.121320,6.578055,4.485549,22.558539,2284.567351,17.562890,1989.710972
Vans Passenger,631.674020,13.000000,14.500000,7.000000,5.000000,23.428162,2375.000000,17.000000,1992.500000
"Vans, Cargo Type",624.214456,12.895833,14.377315,7.324074,4.997917,22.697650,2346.412037,16.928241,2001.837963
"Vans, Passenger Type",648.264752,12.395349,13.877076,7.425249,5.044850,23.789699,2439.534884,16.478405,2002.787375

Now, we add the parameter columns:

In [36]:
vehicles.pivot_table(index=["Vehicle Class"], columns=["Cylinders"], values=['CO2 Emission Grams/Mile'])

                                   CO2 Emission Grams/Mile              \
Cylinders                                             2.0         3.0
Vehicle Class
Compact Cars                                           NaN  243.666667
Large Cars                                             NaN         NaN
Midsize Cars                                           NaN         NaN
Midsize Station Wagons                                 NaN         NaN
Midsize-Large Station Wagons                           NaN         NaN
Minicompact Cars                                493.722222  234.692515
Minivan - 2WD                                          NaN         NaN
Minivan - 4WD                                          NaN         NaN
Small Pickup Trucks                                    NaN         NaN
Small Pickup Trucks 2WD                                NaN         NaN
Small Pickup Trucks 4WD                                NaN         NaN
Small Sport Utility Vehicle 2WD                        NaN         NaN
Small Sport Utility Vehicle 4WD                        NaN         NaN
Small Station Wagons                                   NaN         NaN
Special Purpose Vehicle                                NaN         NaN
Special Purpose Vehicle 2WD                            NaN         NaN
Special Purpose Vehicle 4WD                            NaN         NaN
Special Purpose Vehicles                               NaN  317.392857
Special Purpose Vehicles/2wd                           NaN         NaN
Special Purpose Vehicles/4wd                           NaN         NaN
Sport Utility Vehicle - 2WD                            NaN         NaN
Sport Utility Vehicle - 4WD                            NaN         NaN
Standard Pickup Trucks                                 NaN         NaN
Standard Pickup Trucks 2WD                             NaN         NaN
Standard Pickup Trucks 4WD                             NaN         NaN
Standard Pickup Trucks/2wd                             NaN         NaN
Standard Sport Utility Vehicle 2WD                     NaN         NaN
Standard Sport Utility Vehicle 4WD                     NaN         NaN
Subcompact Cars                                 413.718067  253.757448
Two Seaters                                     510.317927  229.371716
Vans                                                   NaN         NaN
Vans Passenger                                         NaN         NaN
Vans, Cargo Type                                       NaN         NaN
Vans, Passenger Type                                   NaN         NaN

                                                                        \
Cylinders                                 4.0         5.0         6.0
Vehicle Class
Compact Cars                        359.664477  410.342455  448.236147
Large Cars                          378.225886         NaN  439.084500
Midsize Cars                        358.033422  455.120960  443.496348
Midsize Station Wagons              388.835273  440.555715  455.490145
Midsize-Large Station Wagons        433.088892  473.112667  464.888691
Minicompact Cars                    363.662177  394.197189  462.328742
Minivan - 2WD                       421.127016         NaN  474.621148
Minivan - 4WD                              NaN         NaN  504.595699
Small Pickup Trucks                 426.596408         NaN  498.855555
Small Pickup Trucks 2WD             421.974518  494.161681  499.879463
Small Pickup Trucks 4WD             460.204965  494.412536  525.708494
Small Sport Utility Vehicle 2WD     357.035857         NaN  420.886179
Small Sport Utility Vehicle 4WD     371.414286  404.250000  445.067308
Small Station Wagons                362.064456  407.326178  456.330551
Special Purpose Vehicle             462.727273         NaN         NaN
Special Purpose Vehicle 2WD         446.318168         NaN  541.214769
Special Purpose Vehicle 4WD         446.957113         NaN  550.752521
Special Purpose Vehicles            453.016883         NaN  560.834862
Special Purpose Vehicles/2wd        423.190476         NaN  493.722222
Special Purpose Vehicles/4wd               NaN         NaN  522.764706
Sport Utility Vehicle - 2WD         398.989398  488.525146  494.964096
Sport Utility Vehicle - 4WD         420.998147  526.000719  516.446173
Standard Pickup Trucks              468.421444         NaN  561.941022
Standard Pickup Trucks 2WD          438.812497  493.047112  529.386185
Standard Pickup Trucks 4WD          495.638122  515.984305  564.258967
Standard Pickup Trucks/2wd                 NaN         NaN         NaN
Standard Sport Utility Vehicle 2WD  367.846154         NaN  460.848101
Standard Sport Utility Vehicle 4WD  352.421053         NaN  456.910995
Subcompact Cars                     365.346610  436.478241  448.852081
Two Seaters                         368.032758         NaN  456.994452
Vans                                483.864645  563.061152  572.256677
Vans Passenger                             NaN         NaN  522.764706
Vans, Cargo Type                    410.180159         NaN  590.174119
Vans, Passenger Type                503.861161  592.466667  603.095090

                                                                        \
Cylinders                                 8.0         10.0        12.0
Vehicle Class
Compact Cars                        550.880512         NaN  648.289761
Large Cars                          522.153991         NaN  645.151820
Midsize Cars                        545.353319  629.830939  687.734218
Midsize Station Wagons              539.650696         NaN         NaN
Midsize-Large Station Wagons        505.575496         NaN         NaN
Minicompact Cars                    538.091605         NaN  679.324024
Minivan - 2WD                              NaN         NaN         NaN
Minivan - 4WD                              NaN         NaN         NaN
Small Pickup Trucks                        NaN         NaN         NaN
Small Pickup Trucks 2WD             539.101103         NaN         NaN
Small Pickup Trucks 4WD             555.437500         NaN         NaN
Small Sport Utility Vehicle 2WD            NaN         NaN         NaN
Small Sport Utility Vehicle 4WD     549.000000         NaN         NaN
Small Station Wagons                561.226475         NaN         NaN
Special Purpose Vehicle                    NaN         NaN         NaN
Special Purpose Vehicle 2WD         659.251422         NaN         NaN
Special Purpose Vehicle 4WD         689.650798         NaN         NaN
Special Purpose Vehicles            699.146875         NaN         NaN
Special Purpose Vehicles/2wd               NaN         NaN         NaN
Special Purpose Vehicles/4wd               NaN         NaN         NaN
Sport Utility Vehicle - 2WD         586.984933         NaN         NaN
Sport Utility Vehicle - 4WD         622.036464  590.506536         NaN
Standard Pickup Trucks              669.517382         NaN         NaN
Standard Pickup Trucks 2WD          594.703656  928.197778         NaN
Standard Pickup Trucks 4WD          621.707831         NaN         NaN
Standard Pickup Trucks/2wd          687.684524         NaN         NaN
Standard Sport Utility Vehicle 2WD  529.390805         NaN         NaN
Standard Sport Utility Vehicle 4WD  564.974619         NaN  679.000000
Subcompact Cars                     554.586999  683.615385  684.097974
Two Seaters                         569.191132  629.643589  769.237529
Vans                                684.058384         NaN         NaN
Vans Passenger                      740.583333         NaN         NaN
Vans, Cargo Type                    642.127632  751.791667         NaN
Vans, Passenger Type                665.697909  801.704545         NaN


Cylinders                               16.0
Vehicle Class
Compact Cars                             NaN
Large Cars                               NaN
Midsize Cars                             NaN
Midsize Station Wagons                   NaN
Midsize-Large Station Wagons             NaN
Minicompact Cars                         NaN
Minivan - 2WD                            NaN
Minivan - 4WD                            NaN
Small Pickup Trucks                      NaN
Small Pickup Trucks 2WD                  NaN
Small Pickup Trucks 4WD                  NaN
Small Sport Utility Vehicle 2WD          NaN
Small Sport Utility Vehicle 4WD          NaN
Small Station Wagons                     NaN
Special Purpose Vehicle                  NaN
Special Purpose Vehicle 2WD              NaN
Special Purpose Vehicle 4WD              NaN
Special Purpose Vehicles                 NaN
Special Purpose Vehicles/2wd             NaN
Special Purpose Vehicles/4wd             NaN
Sport Utility Vehicle - 2WD              NaN
Sport Utility Vehicle - 4WD              NaN
Standard Pickup Trucks                   NaN
Standard Pickup Trucks 2WD               NaN
Standard Pickup Trucks 4WD               NaN
Standard Pickup Trucks/2wd               NaN
Standard Sport Utility Vehicle 2WD       NaN
Standard Sport Utility Vehicle 4WD       NaN
Subcompact Cars                          NaN
Two Seaters                         873.0625
Vans                                     NaN
Vans Passenger                           NaN
Vans, Cargo Type                         NaN
Vans, Passenger Type                     NaN

Is there any NaN? Why?

In [ ]:
# vehicles.pivot_table(index=["Vehicle Class"], columns=["Cylinders"], values=['CO2 Emission Grams/Mile'])

Let's use the numpy median function

In [41]:
vehicles.pivot_table(index=["Vehicle Class"], values=["Combined MPG","City MPG"], aggfunc=np.median)

                                    City MPG  Combined MPG
Vehicle Class
Compact Cars                            20.0          23.0
Large Cars                              16.0          19.0
Midsize Cars                            18.0          21.0
Midsize Station Wagons                  17.5          20.0
Midsize-Large Station Wagons            17.0          20.0
Minicompact Cars                        18.0          20.0
Minivan - 2WD                           17.0          19.0
Minivan - 4WD                           15.0          18.0
Small Pickup Trucks                     18.0          20.0
Small Pickup Trucks 2WD                 18.0          19.0
Small Pickup Trucks 4WD                 16.0          18.0
Small Sport Utility Vehicle 2WD         21.0          24.0
Small Sport Utility Vehicle 4WD         20.0          22.0
Small Station Wagons                    21.0          24.0
Special Purpose Vehicle                 21.0          22.0
Special Purpose Vehicle 2WD             16.0          18.0
Special Purpose Vehicle 4WD             15.0          16.5
Special Purpose Vehicles                15.0          16.0
Special Purpose Vehicles/2wd            18.5          19.5
Special Purpose Vehicles/4wd            15.5          17.0
Sport Utility Vehicle - 2WD             16.0          18.0
Sport Utility Vehicle - 4WD             15.0          17.0
Standard Pickup Trucks                  14.0          15.0
Standard Pickup Trucks 2WD              15.0          16.0
Standard Pickup Trucks 4WD              14.0          15.0
Standard Pickup Trucks/2wd              12.0          13.0
Standard Sport Utility Vehicle 2WD      16.0          18.0
Standard Sport Utility Vehicle 4WD      15.0          18.0
Subcompact Cars                         19.0          22.0
Two Seaters                             16.0          19.0
Vans                                    14.0          15.0
Vans Passenger                          13.0          14.5
Vans, Cargo Type                        13.0          14.0
Vans, Passenger Type                    12.0          14.0

Here is an example with combined MPG and CO2 emission grams per mile passed to the values argument.

In [42]:
vehicles.pivot_table(index=["Vehicle Class"], values=["Combined MPG", "CO2 Emission Grams/Mile"])

                                    CO2 Emission Grams/Mile  Combined MPG
Vehicle Class
Compact Cars                                     396.758088     23.373385
Large Cars                                       484.391278     18.936854
Midsize Cars                                     432.861095     21.670441
Midsize Station Wagons                           432.128533     21.024038
Midsize-Large Station Wagons                     452.981561     19.924171
Minicompact Cars                                 443.861984     21.028053
Minivan - 2WD                                    469.287896     19.117825
Minivan - 4WD                                    504.595699     17.638298
Small Pickup Trucks                              450.039261     20.257634
Small Pickup Trucks 2WD                          454.361734     19.997506
Small Pickup Trucks 4WD                          497.689565     18.125000
Small Sport Utility Vehicle 2WD                  378.034759     23.818182
Small Sport Utility Vehicle 4WD                  403.410931     22.421053
Small Station Wagons                             383.149627     23.839533
Special Purpose Vehicle                          462.727273     22.000000
Special Purpose Vehicle 2WD                      523.669366     17.726334
Special Purpose Vehicle 4WD                      562.121707     16.558594
Special Purpose Vehicles                         554.603335     16.755698
Special Purpose Vehicles/2wd                     458.456349     19.500000
Special Purpose Vehicles/4wd                     522.764706     17.000000
Sport Utility Vehicle - 2WD                      487.995241     18.824149
Sport Utility Vehicle - 4WD                      531.005884     17.298414
Standard Pickup Trucks                           605.415356     15.241887
Standard Pickup Trucks 2WD                       551.421895     16.542507
Standard Pickup Trucks 4WD                       589.712622     15.372263
Standard Pickup Trucks/2wd                       687.684524     13.000000
Standard Sport Utility Vehicle 2WD               487.407821     18.614525
Standard Sport Utility Vehicle 4WD               505.193154     18.129584
Subcompact Cars                                  414.484391     22.626200
Two Seaters                                      498.090133     19.514013
Vans                                             607.848459     15.121320
Vans Passenger                                   631.674020     14.500000
Vans, Cargo Type                                 624.214456     14.377315
Vans, Passenger Type                             648.264752     13.877076

In this example, we will fill the missing values with zero.

In [43]:
vehicles.pivot_table(index=["Vehicle Class"], columns=["Cylinders"], values=["Combined MPG"], aggfunc='count', fill_value=0)

                                   Combined MPG                              \
Cylinders                                  2.0  3.0   4.0  5.0   6.0   8.0
Vehicle Class
Compact Cars                                  0   12  3399  211  1195   298
Large Cars                                    0    0   145    0   745   714
Midsize Cars                                  0    0  1518   83  1720   665
Midsize Station Wagons                        0    0   157   74   163    22
Midsize-Large Station Wagons                  0    0   330   33   204    66
Minicompact Cars                              1   19   381    9   639   108
Minivan - 2WD                                 0    0    33    0   298     0
Minivan - 4WD                                 0    0     0    0    47     0
Small Pickup Trucks                           0    0   354    0   170     0
Small Pickup Trucks 2WD                       0    0   240   32   113    16
Small Pickup Trucks 4WD                       0    0    78   31    75    16
Small Sport Utility Vehicle 2WD               0    0   251    0   123     0
Small Sport Utility Vehicle 4WD               0    0   280    4   208     2
Small Station Wagons                          0    0  1060   64   221    26
Special Purpose Vehicle                       0    0     1    0     0     0
Special Purpose Vehicle 2WD                   0    0   243    0   229   109
Special Purpose Vehicle 4WD                   0    0    75    0   104    77
Special Purpose Vehicles                      0    1   474    0   621   308
Special Purpose Vehicles/2wd                  0    0     1    0     1     0
Special Purpose Vehicles/4wd                  0    0     0    0     2     0
Sport Utility Vehicle - 2WD                   0    0   511    5   688   411
Sport Utility Vehicle - 4WD                   0    0   418   22   977   660
Standard Pickup Trucks                        0    0   275    0   863  1173
Standard Pickup Trucks 2WD                    0    0   142   30   396   568
Standard Pickup Trucks 4WD                    0    0    56   30   356   517
Standard Pickup Trucks/2wd                    0    0     0    0     0     4
Standard Sport Utility Vehicle 2WD            0    0    13    0    79    87
Standard Sport Utility Vehicle 4WD            0    0    19    0   191   197
Subcompact Cars                              19  128  2434   88  1052   571
Two Seaters                                  28   41   454    0   561   418
Vans                                          0    0   145    6   498   472
Vans Passenger                                0    0     0    0     1     1
Vans, Cargo Type                              0    0     3    0   144   281
Vans, Passenger Type                          0    0     4    1    81   211


Cylinders                          10.0 12.0 16.0
Vehicle Class
Compact Cars                          0   70    0
Large Cars                            0  138    0
Midsize Cars                         17   60    0
Midsize Station Wagons                0    0    0
Midsize-Large Station Wagons          0    0    0
Minicompact Cars                      0   55    0
Minivan - 2WD                         0    0    0
Minivan - 4WD                         0    0    0
Small Pickup Trucks                   0    0    0
Small Pickup Trucks 2WD               0    0    0
Small Pickup Trucks 4WD               0    0    0
Small Sport Utility Vehicle 2WD       0    0    0
Small Sport Utility Vehicle 4WD       0    0    0
Small Station Wagons                  0    0    0
Special Purpose Vehicle               0    0    0
Special Purpose Vehicle 2WD           0    0    0
Special Purpose Vehicle 4WD           0    0    0
Special Purpose Vehicles              0    0    0
Special Purpose Vehicles/2wd          0    0    0
Special Purpose Vehicles/4wd          0    0    0
Sport Utility Vehicle - 2WD           0    0    0
Sport Utility Vehicle - 4WD           4    0    0
Standard Pickup Trucks                0    0    0
Standard Pickup Trucks 2WD            5    0    0
Standard Pickup Trucks 4WD            0    0    0
Standard Pickup Trucks/2wd            0    0    0
Standard Sport Utility Vehicle 2WD    0    0    0
Standard Sport Utility Vehicle 4WD    0    2    0
Subcompact Cars                      17   65    0
Two Seaters                         102  172    8
Vans                                  0    0    0
Vans Passenger                        0    0    0
Vans, Cargo Type                      4    0    0
Vans, Passenger Type                  4    0    0

In [44]:
pd.crosstab(vehicles["Vehicle Class"],vehicles["Cylinders"])

Cylinders,2.0,3.0,4.0,5.0,6.0,8.0,10.0,12.0,16.0
Vehicle Class,,,,,,,,,
Compact Cars,0,12,3399,211,1195,298,0,70,0
Large Cars,0,0,145,0,745,714,0,138,0
Midsize Cars,0,0,1518,83,1720,665,17,60,0
Midsize Station Wagons,0,0,157,74,163,22,0,0,0
Midsize-Large Station Wagons,0,0,330,33,204,66,0,0,0
Minicompact Cars,1,19,381,9,639,108,0,55,0
Minivan - 2WD,0,0,33,0,298,0,0,0,0
Minivan - 4WD,0,0,0,0,47,0,0,0,0
Small Pickup Trucks,0,0,354,0,170,0,0,0,0
Small Pickup Trucks 2WD,0,0,240,32,113,16,0,0,0
Small Pickup Trucks 4WD,0,0,78,31,75,16,0,0,0
Small Sport Utility Vehicle 2WD,0,0,251,0,123,0,0,0,0
Small Sport Utility Vehicle 4WD,0,0,280,4,208,2,0,0,0
Small Station Wagons,0,0,1060,64,221,26,0,0,0
Special Purpose Vehicle,0,0,1,0,0,0,0,0,0
Special Purpose Vehicle 2WD,0,0,243,0,229,109,0,0,0
Special Purpose Vehicle 4WD,0,0,75,0,104,77,0,0,0
Special Purpose Vehicles,0,1,474,0,621,308,0,0,0
Special Purpose Vehicles/2wd,0,0,1,0,1,0,0,0,0
Special Purpose Vehicles/4wd,0,0,0,0,2,0,0,0,0
Sport Utility Vehicle - 2WD,0,0,511,5,688,411,0,0,0
Sport Utility Vehicle - 4WD,0,0,418,22,977,660,4,0,0
Standard Pickup Trucks,0,0,275,0,863,1173,0,0,0
Standard Pickup Trucks 2WD,0,0,142,30,396,568,5,0,0
Standard Pickup Trucks 4WD,0,0,56,30,356,517,0,0,0
Standard Pickup Trucks/2wd,0,0,0,0,0,4,0,0,0
Standard Sport Utility Vehicle 2WD,0,0,13,0,79,87,0,0,0
Standard Sport Utility Vehicle 4WD,0,0,19,0,191,197,0,2,0
Subcompact Cars,19,128,2434,88,1052,571,17,65,0
Two Seaters,28,41,454,0,561,418,102,172,8
Vans,0,0,145,6,498,472,0,0,0
Vans Passenger,0,0,0,0,1,1,0,0,0
"Vans, Cargo Type",0,0,3,0,144,281,4,0,0
"Vans, Passenger Type",0,0,4,1,81,211,4,0,0

## Using cut() to binarize a column

In [50]:
bin_labels_5 = ['Bronze', 'Silver', 'Gold', 'Platinum']
vehicles['levels'] = pd.cut(vehicles['CO2 Emission Grams/Mile'],
                              bins=[0, 300, 500, 700, 1300],
                              labels=bin_labels_5)

In [51]:
vehicles.pivot_table(index='Make', columns='levels', values='Year', aggfunc='count', fill_value=0)

levels                       Bronze  Silver  Gold  Platinum
Make
AM General                        0       0     4         0
ASC Incorporated                  0       0     1         0
Acura                             4     282    16         0
Alfa Romeo                        0      36     5         0
American Motors Corporation       0       8    14         0
...                             ...     ...   ...       ...
Volkswagen                      107     867    73         0
Volvo                             3     677    37         0
Wallace Environmental             0       4    22         6
Yugo                              0       8     0         0
smart                            20       0     0         0

[127 rows x 4 columns]

# Exercise

Build a dataframe with numeric exam marks for the following subjects and find out the student with more A's

- A: 9-10
- B: 7-8
- C: 5-6
- D: 0-4

In [80]:
subjects = ['history', 'english', 'math', 'biology', 'physics', 'chemistry']

In [81]:
# create dataframe
notas = pd.DataFrame(np.random.randint(3, 10, (20,6)))
notas.columns = subjects
notas['student'] = notas.index

In [83]:
# melt (id_vars, var_name, value_name)
notas = notas.melt(id_vars='student', var_name='subject', value_name='mark')

In [88]:
# cut
notas['calification'] = pd.cut(notas.mark, bins=[0,4.9,6.9,8.9,10], labels= ['D','C','B','A'])

In [93]:
# pivot index, columns, values, aggfunc, fill_value, sort
notas.pivot_table(index='student',columns='calification', values='subject', aggfunc='count', fill_value=0).sort_values(by='A', ascending=False)

calification  D  C  B  A
student
12            2  0  1  3
10            0  2  2  2
9             1  2  1  2
5             0  2  2  2
18            1  2  2  1
16            2  2  1  1
13            2  1  2  1
1             2  1  2  1
0             3  1  1  1
7             1  4  0  1
6             1  2  2  1
2             2  0  3  1
8             1  2  3  0
11            1  4  1  0
4             3  2  1  0
14            1  4  1  0
15            2  3  1  0
3             1  1  4  0
17            2  2  2  0
19            3  1  2  0